joint_limits:
  Larm6_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Larm4_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Larm5_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Larm3_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Larm2_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm3_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm1_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm2_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Larm1_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm4_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm5_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6
  Rarm6_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 0.6